controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_cont:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.52
    wheel_radius: 0.16
    use_stamped_vel: false
    enable_odom_tf: true
